name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Nuget Restore
      working-directory: SdlBreakout/SdlBreakout
      run: nuget restore SdlBreakout.vcxproj

    - name: Run MSBuild
      working-directory: SdlBreakout/SdlBreakout
      run: msbuild SdlBreakout.vcxproj
