name: Compile Release
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Nuget Restore
      working-directory: SdlBreakout
      run: nuget restore SdlBreakout.sln -SolutionDirectory .

    - name: Run MSBuild
      working-directory: SdlBreakout
      run: msbuild SdlBreakout.sln -property:Configuration=Release -property:Platform=x64
