name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: MSBuild
      working-directory: SdlBreakout/SdlBreakout
      run: msbuild SdlBreakout.vcxproj
