name: cppcheck
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    container: facthunder/cppcheck
    steps:
      - name: Checkout code
      - uses: actions/checkout@master
        
      - name: Run cppcheck
      - uses: cppcheck --project=sdlbreakout.cppcheck --error-exitcode=1
