name: Compile Debug
on: [push]
jobs:
  build-release:
    runs-on: windows-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Nuget Restore
      working-directory: SdlBreakout
      run: nuget restore SdlBreakout.sln -SolutionDirectory .

    - name: Run MSBuild
      working-directory: SdlBreakout
      run: msbuild SdlBreakout.sln -property:Configuration=Release -property:Platform=x64

  build-debug:
    runs-on: windows-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Nuget Restore
      working-directory: SdlBreakout
      run: nuget restore SdlBreakout.sln -SolutionDirectory .

    - name: Run MSBuild
      working-directory: SdlBreakout
      run: msbuild SdlBreakout.sln -property:Configuration=Debug -property:Platform=x64

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-debug
        path: SdlBreakout/x64/Debug

  test:
    runs-on: windows-latest

    steps: 
    - name: Download debug build output
      uses: actions/download-artifact@v2
      with:
        name: build-debyg
        path: SdlBreakout/x64/Debug
      
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1.1.1
      
    - name: Run Tests
      working-directory: SdlBreakout/x64/Debug
      run: vstest.console Tests.dll
